# Generated by Django 4.2.30 on 2026-04-19 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and spaces allowed.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-/ ]+$', 'Enter a valid username.')], verbose_name='username'),
        ),
    ]
